import os
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.pool import StaticPool
from sqlalchemy import inspect
from app.config import settings
from app.models.base import Base
from app.models.team import Team
from app.models.player import Player
from app.models.stat_definition import StatDefinition
from app.models.stats import (
    BatterSeasonStats,
    PitcherSeasonStats,
    TeamSeasonStats,
    BatterMonthlyStats,
    PitcherMonthlyStats,
)

engine = None
AsyncSessionLocal = None


async def init_db():
    """Initialize database with async support."""
    global engine, AsyncSessionLocal

    database_url = settings.database_url

    if "sqlite" in database_url:
        engine = create_async_engine(
            database_url,
            connect_args={"check_same_thread": False},
            poolclass=StaticPool,
            echo=settings.debug,
        )
    else:
        engine = create_async_engine(
            database_url,
            echo=settings.debug,
            pool_pre_ping=True,
        )

    AsyncSessionLocal = async_sessionmaker(
        engine, class_=AsyncSession, expire_on_commit=False
    )

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    await seed_data()


async def seed_data():
    """Seed initial data into the database."""
    async with AsyncSessionLocal() as session:
        from sqlalchemy import select

        stat_def_exists = (
            await session.execute(select(StatDefinition.id).limit(1))
        ).scalar_one_or_none() is not None
        team_exists = (
            await session.execute(select(Team.id).limit(1))
        ).scalar_one_or_none() is not None

        if stat_def_exists and team_exists:
            return

        batter_stats = [
            StatDefinition(
                stat_key="games",
                display_name_ja="試合数",
                display_name_en="Games",
                category="batter",
                display_order=1,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Number of games played",
            ),
            StatDefinition(
                stat_key="plate_appearances",
                display_name_ja="打席",
                display_name_en="Plate Appearances",
                category="batter",
                display_order=2,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total plate appearances",
            ),
            StatDefinition(
                stat_key="at_bats",
                display_name_ja="打数",
                display_name_en="At Bats",
                category="batter",
                display_order=3,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total at bats",
            ),
            StatDefinition(
                stat_key="hits",
                display_name_ja="安打",
                display_name_en="Hits",
                category="batter",
                display_order=4,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total hits",
            ),
            StatDefinition(
                stat_key="doubles",
                display_name_ja="二塁打",
                display_name_en="Doubles",
                category="batter",
                display_order=5,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total doubles",
            ),
            StatDefinition(
                stat_key="triples",
                display_name_ja="三塁打",
                display_name_en="Triples",
                category="batter",
                display_order=6,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total triples",
            ),
            StatDefinition(
                stat_key="home_runs",
                display_name_ja="本塁打",
                display_name_en="Home Runs",
                category="batter",
                display_order=7,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total home runs",
            ),
            StatDefinition(
                stat_key="rbi",
                display_name_ja="打点",
                display_name_en="RBIs",
                category="batter",
                display_order=8,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Runs batted in",
            ),
            StatDefinition(
                stat_key="runs",
                display_name_ja="得点",
                display_name_en="Runs",
                category="batter",
                display_order=9,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total runs scored",
            ),
            StatDefinition(
                stat_key="strikeouts",
                display_name_ja="三振",
                display_name_en="Strikeouts",
                category="batter",
                display_order=10,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total strikeouts",
            ),
            StatDefinition(
                stat_key="walks",
                display_name_ja="四球",
                display_name_en="Walks",
                category="batter",
                display_order=11,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total walks",
            ),
            StatDefinition(
                stat_key="hit_by_pitch",
                display_name_ja="死球",
                display_name_en="Hit by Pitch",
                category="batter",
                display_order=12,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Times hit by pitch",
            ),
            StatDefinition(
                stat_key="stolen_bases",
                display_name_ja="盗塁",
                display_name_en="Stolen Bases",
                category="batter",
                display_order=13,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total stolen bases",
            ),
            StatDefinition(
                stat_key="batting_average",
                display_name_ja="打率",
                display_name_en="Batting Average",
                category="batter",
                display_order=14,
                decimal_places=3,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Batting average (H/AB)",
            ),
            StatDefinition(
                stat_key="on_base_pct",
                display_name_ja="出塁率",
                display_name_en="On-Base Percentage",
                category="batter",
                display_order=15,
                decimal_places=3,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="On-base percentage",
            ),
            StatDefinition(
                stat_key="slugging_pct",
                display_name_ja="長打率",
                display_name_en="Slugging Percentage",
                category="batter",
                display_order=16,
                decimal_places=3,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Slugging percentage",
            ),
            StatDefinition(
                stat_key="ops",
                display_name_ja="OPS",
                display_name_en="OPS",
                category="batter",
                display_order=17,
                decimal_places=3,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="On-base plus slugging",
            ),
        ]

        # Seed stat definitions for pitchers
        pitcher_stats = [
            StatDefinition(
                stat_key="games",
                display_name_ja="登板数",
                display_name_en="Games",
                category="pitcher",
                display_order=1,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Games pitched in",
            ),
            StatDefinition(
                stat_key="games_started",
                display_name_ja="先発数",
                display_name_en="Games Started",
                category="pitcher",
                display_order=2,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Games started",
            ),
            StatDefinition(
                stat_key="wins",
                display_name_ja="勝利",
                display_name_en="Wins",
                category="pitcher",
                display_order=3,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total wins",
            ),
            StatDefinition(
                stat_key="losses",
                display_name_ja="敗北",
                display_name_en="Losses",
                category="pitcher",
                display_order=4,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total losses",
            ),
            StatDefinition(
                stat_key="saves",
                display_name_ja="セーブ",
                display_name_en="Saves",
                category="pitcher",
                display_order=5,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total saves",
            ),
            StatDefinition(
                stat_key="holds",
                display_name_ja="ホールド",
                display_name_en="Holds",
                category="pitcher",
                display_order=6,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total holds",
            ),
            StatDefinition(
                stat_key="innings_pitched",
                display_name_ja="投球回",
                display_name_en="Innings Pitched",
                category="pitcher",
                display_order=7,
                decimal_places=1,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total innings pitched",
            ),
            StatDefinition(
                stat_key="hits_allowed",
                display_name_ja="安打",
                display_name_en="Hits Allowed",
                category="pitcher",
                display_order=8,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Hits allowed",
            ),
            StatDefinition(
                stat_key="home_runs_allowed",
                display_name_ja="本塁打",
                display_name_en="Home Runs Allowed",
                category="pitcher",
                display_order=9,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Home runs allowed",
            ),
            StatDefinition(
                stat_key="strikeouts",
                display_name_ja="奪三振",
                display_name_en="Strikeouts",
                category="pitcher",
                display_order=10,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total strikeouts",
            ),
            StatDefinition(
                stat_key="walks_allowed",
                display_name_ja="四球",
                display_name_en="Walks Allowed",
                category="pitcher",
                display_order=11,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Walks allowed",
            ),
            StatDefinition(
                stat_key="runs_allowed",
                display_name_ja="失点",
                display_name_en="Runs Allowed",
                category="pitcher",
                display_order=12,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total runs allowed",
            ),
            StatDefinition(
                stat_key="earned_runs",
                display_name_ja="自責点",
                display_name_en="Earned Runs",
                category="pitcher",
                display_order=13,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Earned runs allowed",
            ),
            StatDefinition(
                stat_key="era",
                display_name_ja="防御率",
                display_name_en="ERA",
                category="pitcher",
                display_order=14,
                decimal_places=2,
                sort_direction="asc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Earned run average",
            ),
            StatDefinition(
                stat_key="whip",
                display_name_ja="WHIP",
                display_name_en="WHIP",
                category="pitcher",
                display_order=15,
                decimal_places=2,
                sort_direction="asc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Walks + hits per innings pitched",
            ),
        ]

        # Seed stat definitions for teams
        team_stats = [
            StatDefinition(
                stat_key="games",
                display_name_ja="試合数",
                display_name_en="Games",
                category="team",
                display_order=1,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Games played",
            ),
            StatDefinition(
                stat_key="wins",
                display_name_ja="勝利",
                display_name_en="Wins",
                category="team",
                display_order=2,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total wins",
            ),
            StatDefinition(
                stat_key="losses",
                display_name_ja="敗北",
                display_name_en="Losses",
                category="team",
                display_order=3,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total losses",
            ),
            StatDefinition(
                stat_key="draws",
                display_name_ja="分",
                display_name_en="Draws",
                category="team",
                display_order=4,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Games drawn",
            ),
            StatDefinition(
                stat_key="win_pct",
                display_name_ja="勝率",
                display_name_en="Winning Percentage",
                category="team",
                display_order=5,
                decimal_places=3,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Winning percentage",
            ),
            StatDefinition(
                stat_key="runs_scored",
                display_name_ja="得点",
                display_name_en="Runs Scored",
                category="team",
                display_order=6,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total runs scored",
            ),
            StatDefinition(
                stat_key="runs_allowed",
                display_name_ja="失点",
                display_name_en="Runs Allowed",
                category="team",
                display_order=7,
                decimal_places=0,
                sort_direction="asc",
                is_ranking_eligible=False,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total runs allowed",
            ),
            StatDefinition(
                stat_key="home_runs",
                display_name_ja="本塁打",
                display_name_en="Home Runs",
                category="team",
                display_order=8,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total home runs",
            ),
            StatDefinition(
                stat_key="stolen_bases",
                display_name_ja="盗塁",
                display_name_en="Stolen Bases",
                category="team",
                display_order=9,
                decimal_places=0,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=False,
                description="Total stolen bases",
            ),
            StatDefinition(
                stat_key="team_batting_avg",
                display_name_ja="打率",
                display_name_en="Team Batting Average",
                category="team",
                display_order=10,
                decimal_places=3,
                sort_direction="desc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Team batting average",
            ),
            StatDefinition(
                stat_key="team_era",
                display_name_ja="防御率",
                display_name_en="Team ERA",
                category="team",
                display_order=11,
                decimal_places=2,
                sort_direction="asc",
                is_ranking_eligible=True,
                is_comparable=True,
                is_graphable=True,
                is_rate_stat=True,
                description="Team earned run average",
            ),
        ]

        npb_teams = [
            Team(
                code="g",
                name_ja="読売ジャイアンツ",
                name_en="Yomiuri Giants",
                short_name="Giants",
                league="central",
            ),
            Team(
                code="t",
                name_ja="阪神タイガース",
                name_en="Hanshin Tigers",
                short_name="Tigers",
                league="central",
            ),
            Team(
                code="c",
                name_ja="広島東洋カープ",
                name_en="Hiroshima Carp",
                short_name="Carp",
                league="central",
            ),
            Team(
                code="d",
                name_ja="中日ドラゴンズ",
                name_en="Chunichi Dragons",
                short_name="Dragons",
                league="central",
            ),
            Team(
                code="s",
                name_ja="東京ヤクルトスワローズ",
                name_en="Tokyo Yakult Swallows",
                short_name="Swallows",
                league="central",
            ),
            Team(
                code="db",
                name_ja="横浜DeNAベイスターズ",
                name_en="Yokohama DeNA BayStars",
                short_name="BayStars",
                league="central",
            ),
            Team(
                code="h",
                name_ja="福岡ソフトバンクホークス",
                name_en="Fukuoka SoftBank Hawks",
                short_name="Hawks",
                league="pacific",
            ),
            Team(
                code="e",
                name_ja="東北楽天ゴールデンイーグルス",
                name_en="Tohoku Rakuten Golden Eagles",
                short_name="Eagles",
                league="pacific",
            ),
            Team(
                code="l",
                name_ja="埼玉西武ライオンズ",
                name_en="Saitama Seibu Lions",
                short_name="Lions",
                league="pacific",
            ),
            Team(
                code="m",
                name_ja="千葉ロッテマリーンズ",
                name_en="Chiba Lotte Marines",
                short_name="Marines",
                league="pacific",
            ),
            Team(
                code="f",
                name_ja="北海道日本ハムファイターズ",
                name_en="Hokkaido Nippon Ham Fighters",
                short_name="Fighters",
                league="pacific",
            ),
            Team(
                code="b",
                name_ja="オリックス・バファローズ",
                name_en="Orix Buffaloes",
                short_name="Buffaloes",
                league="pacific",
            ),
        ]

        did_change = False

        if not stat_def_exists:
            session.add_all(batter_stats + pitcher_stats + team_stats)
            did_change = True

        if not team_exists:
            session.add_all(npb_teams)
            did_change = True

        if did_change:
            await session.commit()


async def get_session() -> AsyncSession:
    """Get database session for dependency injection."""
    async with AsyncSessionLocal() as session:
        yield session


async def close_db():
    """Close database connection."""
    if engine:
        await engine.dispose()
